Prevented domain field from being set on multi license services
blesta/module-cwatch pull request #37
Opened 2019-01-02 19:14 UTC by JReissmueller

Unset the domain validation rule for multi license services
Added missing language to client interface

Fixes #35 
Fixes #36

2019-01-02 23:33 UTC, tysonphillips requested changes

2019-01-02 23:33 UTC, tysonphillips commented on cwatch.php
>                              "/^([a-z0-9]|[a-z0-9][a-z0-9\-]{0,61}[a-z0-9])(\.([a-z0-9]|[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]))+$/"
Shouldn't the domain name be case-insensitive? This regex could include a "/i" for that. I suppose you may want to also update other locations to save the domain in lower-case.

2019-01-03 00:25 UTC, JReissmueller commented on cwatch.php
>                              "/^([a-z0-9]|[a-z0-9][a-z0-9\-]{0,61}[a-z0-9])(\.([a-z0-9]|[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]))+$/"
Updated that and fixed a couple if statements where the condition was reversed

2019-01-07 21:03 UTC, tysonphillips approved these changes

2019-01-07 23:20 UTC, merged